fixed messages for not defined variables
beachbodydigital/ludicrousdb pull request #1
Opened 2019-09-23 18:27 UTC by omalave

I created a simple fix for those not defined variables, that prevent to "php compact function" throw notices and warnings.

2019-09-23 20:47 UTC, ChristianOrralaBB approved these changes
Ok, just setting the value to null, this should prevent the warnings and notices.

2019-09-23 20:56 UTC, thefrosty commented
I'd like to test this before you merge. Please allow me a day to get this tested locally.

2019-09-23 20:56 UTC, thefrosty requested changes
Needs to be tested locally before approval.

2019-09-25 18:49 UTC, thefrosty approved these changes

2019-09-25 19:38 UTC, merged